### ISSUE TITLE
capn_write_mem() return value is int

### ISSUE THREAD

**Issue by QQNN-blue** [opensourcerouting/c-capnproto#40]
capn_write_mem()'s return value is int.
- The return value is actually down-cast from size_t, since inside capn_write_mem(), the actual header and data sizes are size_t.
- the int type of the return value basically limits the size of a capnproto file to 2GB.

**Comment by detly** [comment]
It looks like this is so that functions can also return `-1` to signify an error (a practice that I am not a fan of but nonetheless am familiar with). The easiest change is probably to use `ssize_t`, but this breaks from the ANSI standard (it's a POSIX type). The signed `long` type could suffice instead to remain ANSI compatible.

An API-breaking change could be to return a success or failure value (eg. true or false), and to return the size via pointer.

**Comment by QQNN-blue** [comment]
thanks @detly . I think a signed `long` return type could be a good compromise.

**Comment by QQNN-blue** [comment]
@detly should i open a PR with this change?

**Comment by detly** [comment]
> @detly should i open a PR with this change?

Yes please! PRs on this repo appear to be going unmerged, but I am open to taking over if the current maintainer doesn't want to continue with it themselves. At that point I'll go through any backlog of PRs here.

**Comment by eqvinox** [comment]
@detly I've sent you an invite with maintenance access;  you're free to proceed as you'd like.  Anyone else who'd like access can ping me too.  Of course, you can also fork and continue elsewhere, I'd be happy to point people along to any actively maintained repo. 

Story on our end is:  we prototyped a larger system using Cap'n Proto from C, but ended up going a completely different route.  We actually have a second code generator for C-capnp internally, written in python instead of C, but it's intimately tied to that prototyped design which never saw the light of the outside world...

**Comment by detly** [comment]
> We actually have a second code generator for C-capnp internally, written in python instead of C

I actually thought about doing this! I was inspired by [this Meson FAQ entry](https://mesonbuild.com/FAQ.html#why-is-meson-implemented-in-python-rather-than-programming-language-x). Do you use a templating engine like Jinja2?

I'm happy to continue development here until there's a reason to move it. If you have any notes or outstanding changes you've wanted to hand over, let me know. I might also email the Cap'n Proto group at some point and introduce myself.

Thanks for your hard work so far!

**Comment by QQNN-blue** [comment]
thanks @detly .

Hi @eqvinox , how do I get the permission to open a PR? seems that I don't have the access right to do so.

**Comment by detly** [comment]
@QQNN-blue I didn't need any special permissions to open a PR. Point me to your fork and I'll have a look.

**Comment by QQNN-blue** [comment]
@detly Hi Jason, sorry for getting back you late. Finally figured out why - I used my working computer which is configured for the private github server, so I can't push anything to github.com. 

I opened the PR #47 to solve this issue. Please let me know if there is any concern of that PR.
